kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: role-test
 namespace: role
subjects:
- kind: User
  name: user3
  apiGroup: ""
roleRef:
  kind: Role
  name: user3-role
  apiGroup: ""
