
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:       
   namespace: role
   name: user3-role    
rules:
- apiGroups: ["", "extensions", "apps"]    
  resources: ["deployments", "pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
